GET http://localhost:8080/api/taxis?page=1&pageSize=10&query=ab HTTP/1.1
content-type: application/json

GET http://localhost:8080/api/trajectories/9534?date=2008-02-02 HTTP/1.1
content-type: application/json
